# Generated by Django 3.2.23 on 2023-12-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_teacheractivities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheractivities',
            name='student_interaction_rating',
            field=models.CharField(max_length=5),
        ),
    ]
